import { Dimensions, StyleSheet } from 'react-native';
import { darkColors } from './theme';

// Use darkColors as default for static StyleSheet (screens override with useTheme)
const colors = darkColors;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  topBar: {
    height: 64,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    backgroundColor: colors.surface,
    zIndex: 50,
  },
  topBarLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  appTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.onSurface,
  },
  screenTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.onSurface,
  },
  screen: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 8,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    color: colors.onSurfaceVariant,
    opacity: 0.5,
  },
  placeholderText: {
    color: colors.onSurfaceVariant,
  },
  labelSmall: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.zinc500,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
  },
  heading: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.onSurface,
    marginTop: 4,
  },
  balanceCard: {
    padding: 24,
    borderRadius: 32,
    marginBottom: 24,
    overflow: 'hidden',
  },
  balanceLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: 'rgba(199,210,254,0.7)',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  balanceAmount: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#fff',
    marginTop: 4,
  },
  balanceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 32,
  },
  balanceSubLabel: {
    fontSize: 10,
    color: colors.white60,
    textTransform: 'uppercase',
  },
  balanceSubValue: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#fff',
  },
  balanceDivider: {
    width: 1,
    height: 24,
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 1,
    color: colors.zinc400,
  },
  sectionAction: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.indigo400,
  },
  catCard: {
    backgroundColor: colors.white5,
    borderWidth: 1,
    borderColor: colors.white10,
    borderRadius: 24,
    padding: 16,
    marginBottom: 12,
  },
  catRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  catLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  catIconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.white5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  catName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: colors.onSurface,
  },
  catSub: {
    fontSize: 10,
    color: colors.zinc500,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  catSpent: {
    fontSize: 14,
    fontWeight: 'bold',
    color: colors.onSurface,
  },
  catBudget: {
    fontSize: 10,
    color: colors.zinc500,
  },
  progressBg: {
    height: 6,
    width: '100%',
    backgroundColor: colors.white5,
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: {
    height: 6,
    borderRadius: 3,
  },
  historyCard: {
    backgroundColor: colors.white5,
    borderWidth: 1,
    borderColor: colors.white10,
    borderRadius: 24,
    padding: 16,
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  expAmount: {
    fontSize: 14,
    fontWeight: 'bold',
    color: colors.rose400,
  },
  deleteBtn: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: 'rgba(251,113,133,0.1)',
  },
  bottomNav: {
    position: 'absolute',
    bottom: 32,
    left: '5%',
    right: '5%',
    height: 64,
    backgroundColor: 'rgba(24,24,27,0.9)',
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 16,
    borderTopWidth: 1,
    borderTopColor: colors.white5,
    zIndex: 40,
  },
  navTab: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  navLabel: {
    fontSize: 9,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    marginTop: 2,
  },
  fabCenter: {},
  fabText: {},
  fab: {
    position: 'absolute',
    bottom: 110,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#6366f1',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 45,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
  catGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  catSelectBtn: {
    width: (Dimensions.get('window').width - 48 - 24) / 3,
    borderRadius: 24,
    overflow: 'hidden',
  },
  catSelectInner: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
  },
  catSelectLabel: {
    fontSize: 10,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    marginTop: 8,
    letterSpacing: 0.5,
  },
  noteInput: {
    height: 56,
    backgroundColor: colors.white5,
    borderWidth: 1,
    borderColor: colors.white5,
    borderRadius: 16,
    paddingHorizontal: 16,
    color: colors.onSurface,
    fontSize: 14,
  },
  addCatItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.white5,
    borderWidth: 1,
    borderColor: colors.white10,
    borderRadius: 14,
    padding: 12,
    marginBottom: 8,
  },
  addCatItemSelected: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(99,102,241,0.06)',
  },
  submitBtn: {
    height: 56,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  submitText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 18,
  },
  budgetTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    color: colors.onSurface,
  },
  budgetMonth: {
    fontSize: 14,
    color: colors.zinc500,
    marginTop: 4,
  },
  budgetSummaryCard: {
    backgroundColor: colors.white5,
    borderWidth: 1,
    borderColor: colors.white10,
    borderRadius: 16,
    padding: 20,
    marginTop: 20,
    marginBottom: 28,
  },
  budgetSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  budgetSummaryLabel: {
    fontSize: 11,
    color: colors.zinc500,
    marginBottom: 4,
  },
  budgetSummaryAmount: {
    fontSize: 28,
    fontWeight: 'bold',
    color: colors.onSurface,
  },
  budgetSummaryBudget: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.onSurface,
  },
  budgetProgressBg: {
    height: 6,
    width: '100%',
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 3,
    overflow: 'hidden',
  },
  budgetProgressFill: {
    height: 6,
    borderRadius: 3,
  },
  budgetPercentText: {
    fontSize: 12,
    color: colors.zinc500,
    textAlign: 'right',
    marginTop: 8,
  },
  budgetCatHeader: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.onSurface,
    marginBottom: 12,
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white5,
    borderWidth: 1,
    borderColor: colors.white10,
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 44,
    marginBottom: 16,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    color: colors.onSurface,
    fontSize: 14,
    height: 44,
  },
  budgetCatCard: {
    backgroundColor: colors.white5,
    borderWidth: 1,
    borderColor: colors.white10,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  budgetCatTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  budgetCatName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.onSurface,
  },
  budgetEditBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  budgetCatBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  budgetCatSpent: {
    fontSize: 13,
    color: colors.onSurface,
  },
  budgetCatLimit: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.onSurface,
  },
  settingsCard: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 4,
  },
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
  },
});

export const homeS = StyleSheet.create({
  card: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 18,
    marginBottom: 14,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 4,
  },
  monthBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
  },
  progressBg: {
    height: 8,
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 4,
  },
  barContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    height: 170,
    marginTop: 16,
    paddingBottom: 4,
  },
  bar: {
    width: 36,
  },
  catRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
  },
  catIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export const stl = StyleSheet.create({
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(99,102,241,0.08)',
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1,
    marginTop: 24,
    marginBottom: 10,
    paddingHorizontal: 4,
  },
});

export const catStyles = StyleSheet.create({
  addCard: {
    borderWidth: 2,
    borderStyle: 'dashed',
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    marginBottom: 12,
  },
  addIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  catCard: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  catCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  modalBox: {
    width: '85%',
    borderRadius: 20,
    padding: 24,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 16,
  },
  modalInput: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    fontSize: 15,
  },
  modalBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
  },
  typeBtn: {
    paddingVertical: 8,
    paddingHorizontal: 18,
    borderRadius: 10,
  },
});
